add seeds & 2 methods
gluuck/TestGuru pull request #3
Opened 2021-10-28 06:38 UTC by gluuck

2021-10-30 10:28 UTC, VidgarVii requested changes

2021-10-30 10:28 UTC, VidgarVii commented on app/models/test.rb
> +	end
можно сделать блокчейн более читаемым
```
joins('JOIN categories ON tests.category_id = categories.id')
  .where(categories: { title: title })
  .order(title: :desc)
  .pluck(:title)
```

2021-10-30 10:28 UTC, VidgarVii commented on db/migrate/20211024085649_create_tests.rb
> +      t.references :user, null: false
не исправил

2021-10-30 10:28 UTC, VidgarVii commented on app/models/user.rb
> +	end
1 тут надо возвращать сами тесты, а не их названия
2 метод не вернёт список пройденных тестов
Почему не используешь таблицу результатов?

2021-10-30 10:28 UTC, VidgarVii commented on db/seeds.rb
> +])
Большое кол-во не нужных запросов в БД. Это замедлит заполнение БД и даст лишнюю нагрузку. Метод create! возвращает relation Который можно уже использовать для объявления связей

2021-10-30 10:29 UTC, VidgarVii commented
ассоциации в моделях объявлены не полностью и не корректно. Лучше пока их убрать

2021-10-31 11:05 UTC, VidgarVii requested changes

2021-10-31 11:05 UTC, VidgarVii commented on app/models/user.rb
>    end
этот метод не возвращает пройденные или который начал проходить юзер тесты.  Начал верно но не закончил. Тестируй код который пишешь

2021-11-01 06:33 UTC, VidgarVii requested changes

2021-11-01 06:33 UTC, VidgarVii commented on app/models/user.rb
> +  def find_by_level(level, id)
id передавать нет смысла. Так как вызывая метод мы обращаемся к объекту экземпляра класса User. И все атрибуты и так в открытом доступе текущего объекта.

2021-11-01 06:56 UTC, gluuck commented on app/models/user.rb
> +  def find_by_level(level, id)
если  не передавать id то по умолчанию  user_id = 1

2021-11-02 10:38 UTC, merged