results & answers
gluuck/TestGuru pull request #9
Opened 2021-11-16 14:55 UTC by gluuck

2021-11-16 18:56 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i[ show edit update destroy ]
%i[show edit update destroy]

2021-11-16 18:56 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    def set_answer
для приватных методов не нужны лишние отступы

2021-11-16 18:56 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: :start
для 1 экшена колбек не пишут. Ухудшает читаемость кода

2021-11-16 18:56 UTC, VidgarVii commented on app/models/result.rb
> +  end
протестируй момент когда юзер не выбирает ответ и жмет далее

2021-11-16 19:02 UTC, VidgarVii requested changes

2021-11-16 19:02 UTC, VidgarVii commented on app/models/result.rb
> +    test.questions.order(:id).where('id > ?', current_question.id).first
установка current_question у тебя размазана в 3х местах класса. Хорошо бы эту логику вынести в отдельный метод. Как раз уместно в next_question. И вызывать только его через колбек

2021-11-17 04:47 UTC, gluuck commented on app/models/result.rb
> +    test.questions.order(:id).where('id > ?', current_question.id).first
1. Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова, не знаю зачем но если пишут наверное надо тогда.

2021-11-17 14:35 UTC, VidgarVii commented on app/models/result.rb
> +    test.questions.order(:id).where('id > ?', current_question.id).first
давай еще раз.
Задача назначение следующего вопроса. 
Это мы делаем определяя current_question. Делаем всего 1 колбек который будет отвечать за эту фичу
и вызываем его до валидации

```ruby
def set_current_question
  self.current_question = next_question
end
```
А всю логику получения следующего вопроса пишем в next_question

```ruby
def next_question
  if new_record?
    test.questions.first if test.present?
  else
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end
```
И вся фича в 1 месте. А сейчас у тебя она раскидана по разным местам кода. Такой неизбежно приведёт к багам

2021-11-17 14:35 UTC, VidgarVii commented on app/models/result.rb
> +    self.correct_question += 1 if correct_answer?(answer_ids)
correct_question кол-во чего-либо нибудь обычно пишут во множественном числе

2021-11-18 06:28 UTC, merged